export const FETCH_RENTALS = 'FETCH_RENTALS';
export const FETCH_RENTAL_FIND_BY_ID = 'FETCH_RENTAL_FIND_BY_ID';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';
